#!/usr/bin/bash

# Use this `release` script to `elm-test` and `elm make` this project.

LOCAL_DIST_DIR=dist

./doc.py
elm-test &&
    elm make src/Main.elm --optimize --output $LOCAL_DIST_DIR/js/pancake.js
